version: "3.8"
services:
  frontend:
    build: ./backend
    container_name: backend_C
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  backend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
